version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout:
          post:
	      - cp -r licences/. $ANDROID_HOME/licenses
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
